language: clojure
script: echo "deploy"
notifications:
  email: false
deploy:
- provider: script
  skip_cleanup: true
  script: lein release :patch
  on:
    branch: master
env:
  global:
  - secure: B2CYQaWuRbPY2mxT+sxdoTUyAG91Z9JR6+KWuOxX7UuncDdi8cPiY8fOCnlKMN+5WI8ET1P3qkgb34JGA+ZVhw7swoK5B8duf2Rpo+Tt9SytxNlyaQhoTESI1uesV6qUOObueMqXoQ98+PFZA0PWGM53XQRYkBvNsDPrLyOWUFxIRmM8m05HxzPc/Z5myupZjwVjKy7oFoFrdNRGojQITDem4/0Ao2ICl6A96PfUKGWleXMvp0VbQlee55PN8AwzkYgoe+yDS0qHJ5KSZTMA479J87ZoZFIO04BVeHc1NweiJ+RTym922iRnTe29eK7val0TxOXp1cNqrV8PxMkZSQPADAW90a0TNx9DjkJjkEvxCetevqpCg+TIiB7X5wbgwt96Qb9bDQrnhUFE67UWRIPP+crDGjZfRuWNBPr5MlClF0u+8CfG/ydoogg0vYtTtBqqgGKM9c76j/QSXE5PNlmbHGV75xTC5wga2XQEwjkXAlL5OEbvF+qhjBqyT8/2VTLVG/EAonjuAnYsGDbMjDlGUnf1PeBWeqIIeOyXIeOcgddORnlT2bZVVXeJ9dp/2xRn1cK2fQ3Aq86j/qtYdNO6fdkUURWJQJrguzLdo2LSlBOGdz4U2OVAUaN5MjXnHXwu7lg4Ux3RsMGF0Jli4wnpN277ehGXiLJhd40HNd8=
  - secure: V6Ag23J4gLuzfiWBWdwEGQHJCU2CLYMpYZ5/BGDbELWd+zSA40pPkLoB4TM/HXfFgg3dkLAUogZidpo/NHsSjRP0xBISlBW9JJL5iyDecuI3aCgUzk9q1YAlI8GAUnMnnGyElysGZOawv0XjK4ieABJq1+NpZn76cirxSHt+fdJ+h4kye0O153DC2ELjcfg9mjObudCYoU6Q+M9Cdu/5dGksTdOG1tvZUL9f2no6bbX+X4PKf3ojpdzreL42z8hhyRlna5geo0BGKHZ7sProJW6QbBhhcIf5C7gfrV20hHiQiZIEAOz9KFHX/e6DDaOUv/4Ku7rMRhX2Vce+9W1mGJ+QV4deMbBBvdBUrdpRtAzhSuRH+JWQPeomQQxg9CVk1qQmwTItoL68SQ6qHONrgw+rhyqfq4qVKWx1vhg+CjPLnPjFGtWqVqUNV3tI2mVKhZbHyHYI+5AHo4KavjvGRin3hNEn1LBD9yexLS8q8V+HFMCUoAIv1/5kQ+qMDOTdMlpCsPILc+J8NHDGz7dLbn824Cf+16kMp1BKHU0uw/KvYzSCIDuTB/EJGGINMKdJfKgsLDu1sB2Owz4M0AaPGoHCixn/wh2PDZFGgGV69kyV9mx3YACedrHm+2vsSP+YDeJOVcRBFE+gW+b5aCeBnaml6mZqpNi/U8wlu/FZqY0=
